### ISSUE TITLE
现代隐私保护指南的在线阅读链接指向可能错误

### ISSUE THREAD

**Issue by BigBrotherJu** [KagarinoKirieStudio/KagarinoKirieStudio#1]
现代隐私保护指南后面的在线阅读现在指向了 [https://github.com/ArchLinuxStudio/ModernSecurityProtectionGuide](https://github.com/ArchLinuxStudio/ModernSecurityProtectionGuide)，根据另外三个教程的在线阅读链接，现代隐私保护指南后面的在线阅读应该指向 [https://archlinuxstudio.github.io/ModernSecurityProtectionGuide/#/](https://archlinuxstudio.github.io/ModernSecurityProtectionGuide/#/)。

**Comment by ryosukeeeeee** [comment]
@BigBrotherJu Thank you, and I will fix it.

**Comment by ryosukeeeeee** [comment]
https://github.com/ArchLinuxStudio/ArchLinuxStudio.github.io/commit/29e588ad3642a82b1f747e94bb8bc777794b1268
